"""Tests for AudioTagger — Picard tag read/write mapping across FLAC/MP3/M4A.

Reads the committed fixtures in ``tests/fixtures/library/`` (generated by
``generate.py`` with raw mutagen — an independent oracle). Write/roundtrip tests
copy a fixture to a tmp path so the committed files stay pristine.
"""

import shutil
from pathlib import Path

import pytest

from infrastructure.audio.tagger import AudioTagger
from models.audio import AudioTag

FIXTURES = Path(__file__).resolve().parent.parent / "fixtures" / "library"

# A tiny but valid PNG-ish blob — enough to roundtrip as cover-art bytes.
_COVER = b"\x89PNG\r\n\x1a\n" + b"\x00" * 96


@pytest.fixture
def tagger() -> AudioTagger:
    return AudioTagger()


@pytest.fixture
def tmp_copy(tmp_path: Path):
    def _copy(name: str) -> Path:
        dest = tmp_path / name
        shutil.copy(FIXTURES / name, dest)
        return dest

    return _copy


# -- read: Picard MBID mapping per format --


def test_read_flac_release_group_id(tagger):
    tag, _ = tagger.read_tags(FIXTURES / "flac_full_01.flac")
    assert tag.musicbrainz_release_group_id == "b1392450-e666-3926-a536-22c65f834433"


def test_read_mp3_release_group_id(tagger):
    tag, _ = tagger.read_tags(FIXTURES / "mp3_full_01.mp3")
    assert tag.musicbrainz_release_group_id == "rg-achtung-0001"


def test_read_m4a_release_group_id(tagger):
    tag, _ = tagger.read_tags(FIXTURES / "m4a_full_01.m4a")
    assert tag.musicbrainz_release_group_id == "rg-mezzanine-0001"


def test_read_flac_all_mbid_fields(tagger):
    tag, _ = tagger.read_tags(FIXTURES / "flac_full_01.flac")
    assert tag.musicbrainz_release_id == "0da3b3e3-1111-4444-8888-aaaaaaaaaaaa"
    assert tag.musicbrainz_recording_id == "rec-airbag-0001"
    assert tag.musicbrainz_artist_id == "a74b1b7f-71a5-4011-9441-d0b5e4122711"
    assert tag.acoustid_id == "ac-airbag-0001"


def test_read_descriptive_fields(tagger):
    tag, _ = tagger.read_tags(FIXTURES / "flac_full_01.flac")
    assert (tag.title, tag.artist, tag.album, tag.album_artist) == (
        "Airbag",
        "Radiohead",
        "OK Computer",
        "Radiohead",
    )
    assert tag.track_number == 1
    assert tag.year == 1997


def test_read_audio_info(tagger):
    _, info = tagger.read_tags(FIXTURES / "flac_full_01.flac")
    assert info.file_format == "flac"
    assert info.sample_rate == 44100
    assert info.bit_depth == 16  # FLAC is lossless
    assert info.channels == 2
    assert info.file_size_bytes > 0


def test_read_mp3_info_has_no_bit_depth(tagger):
    _, info = tagger.read_tags(FIXTURES / "mp3_full_01.mp3")
    assert info.file_format == "mp3"
    assert info.bit_depth is None  # lossy


def test_read_m4a_info_has_no_bit_depth(tagger):
    # MP4Info.bits_per_sample is 16 even for lossy AAC — must be suppressed.
    _, info = tagger.read_tags(FIXTURES / "m4a_full_01.m4a")
    assert info.file_format == "m4a"
    assert info.bit_depth is None


# -- read: compilation flag per format --


def test_compilation_flag_flac(tagger):
    tag, _ = tagger.read_tags(FIXTURES / "flac_compilation_01.flac")
    assert tag.compilation is True
    assert tag.album_artist == "Various Artists"


def test_non_compilation_flag(tagger):
    tag, _ = tagger.read_tags(FIXTURES / "flac_full_01.flac")
    assert tag.compilation is False


# -- read: edge cases --


def test_mp3_recording_id_is_stored_as_ufid_not_release_track(tagger, tmp_copy):
    # The recording MBID must live in the UFID frame (Picard), never the
    # "Release Track Id" TXXX — that's a different MusicBrainz entity.
    import mutagen

    raw = mutagen.File(tmp_copy("mp3_full_01.mp3"))
    assert "UFID:http://musicbrainz.org" in raw.tags
    assert "TXXX:MusicBrainz Release Track Id" not in raw.tags


def test_only_release_mbid_leaves_release_group_none(tagger):
    tag, _ = tagger.read_tags(FIXTURES / "flac_only_release_mbid.flac")
    assert tag.musicbrainz_release_group_id is None
    assert tag.musicbrainz_release_id == "rel-only-0001"


def test_cjk_tags_preserved(tagger):
    tag, _ = tagger.read_tags(FIXTURES / "flac_cjk_01.flac")
    assert tag.artist == "ユキ"
    assert tag.title == "桃源へ"


def test_no_tags_yields_empty_strings(tagger):
    tag, _ = tagger.read_tags(FIXTURES / "flac_no_tags.flac")
    assert tag.title == ""
    assert tag.artist == ""
    assert tag.musicbrainz_release_group_id is None


def test_unreadable_file_raises(tagger, tmp_path):
    junk = tmp_path / "not-audio.flac"
    junk.write_bytes(b"this is not audio")
    with pytest.raises(ValueError):
        tagger.read_tags(junk)


# -- write: roundtrip per format --


@pytest.mark.parametrize("name", ["flac_full_01.flac", "mp3_full_01.mp3", "m4a_full_01.m4a"])
def test_write_mb_tags_roundtrip(tagger, tmp_copy, name):
    path = tmp_copy(name)
    new = AudioTag(
        title="New Title",
        artist="New Artist",
        album="New Album",
        album_artist="New AA",
        track_number=7,
        disc_number=2,
        year=2020,
        genre="Jazz",
        musicbrainz_release_group_id="rg-new",
        musicbrainz_release_id="rel-new",
        musicbrainz_recording_id="rec-new",
        musicbrainz_artist_id="art-new",
        musicbrainz_album_artist_id="aart-new",
        acoustid_id="ac-new",
        compilation=True,
    )
    tagger.write_mb_tags(path, new)
    back, _ = tagger.read_tags(path)
    assert back.title == "New Title"
    assert back.track_number == 7
    assert back.disc_number == 2
    assert back.year == 2020
    assert back.genre == "Jazz"
    assert back.compilation is True
    assert back.musicbrainz_release_group_id == "rg-new"
    assert back.musicbrainz_recording_id == "rec-new"
    assert back.musicbrainz_artist_id == "art-new"
    assert back.musicbrainz_album_artist_id == "aart-new"
    assert back.acoustid_id == "ac-new"


@pytest.mark.parametrize("name", ["flac_full_01.flac", "mp3_full_01.mp3", "m4a_full_01.m4a"])
def test_cover_art_roundtrip(tagger, tmp_copy, name):
    path = tmp_copy(name)
    tagger.write_cover_art(path, _COVER)
    assert tagger.read_cover_art(path) == _COVER
